### ISSUE TITLE
Errors in IOS

### ISSUE THREAD

**Issue by skyRino** [RoboPai/sdm#2]
Great job first, but when i added the src codes in my ios project, there are some errors

it shows that:

ld: 26 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you please tell me that why the src can not work well.

thx!

**Comment by skyRino** [comment]
BTW, my environment is Xcode8, OS X 10.11.6

**Comment by RoboPai** [comment]
Have you added the OpenCV2.framework to your ios project? And can you esaily read camera with OpenCV in iOS?

**Comment by skyRino** [comment]
Yes, I added the framework and I can detect the face from camera in my framework with OpenCV.

**Comment by RoboPai** [comment]
Can I have a look your ViewController.mm?

**Comment by RoboPai** [comment]
sorry, you should add the include folder under src to you iOS Project source code folder, not adding src folder, and just copy "include" to "project src". and then "#include "include/ldmarkmodel.h" " in you .mm file, and then use it like test_model.cpp. you can't "#include "include/ldmarkmodel.h" " in you .h file.

**Comment by RoboPai** [comment]
1.Copy "haar_roboman_ff_alt2.xml" & "roboman-landmark-model.bin" to your iOS Project.

2.Add the OpenCV2.framework to you iOS Project, make sure you can easily read camera and show frame with OpenCV.

3.Copy the include folder under src folder to you iOS Project source code, just copy, not anything else.

4.And then "#include "include/ldmarkmodel.h"" in your .mm file, make sure not in .h file, use it like test_model.cpp, Compile & enjoy it.

**Comment by skyRino** [comment]
ok, thank you, i will try it.

**Comment by skyRino** [comment]
Sorry, there still are these errors.

Could you please share your ios project if it is possible?

**Comment by RoboPai** [comment]
Ok, Can you guarantee non-commercial use?
If yes, I can share my iOS project  to you later.

**Comment by skyRino** [comment]
I rebuild a new project and setup as the guide but the errors are still there.

I can guarantee non-commercial use.  I just use this for academic research cause I am a PHD student.

Thanks a lot for your kindness.

**Comment by RoboPai** [comment]
what's your email address?

**Comment by skyRino** [comment]
luonan@outlook.com
Thx again

**Comment by cpfe532** [comment]
Hi RoboPai, I got the same problem when compiling the project based on your instruction. I am not for commercial purpose also. May I have the project also? I would like to see the performance on mobile devices. Thanks.
