### ISSUE TITLE
Training sample size

### ISSUE THREAD

**Issue by cpfe532** [RoboPai/sdm#21]
I am running the training code. I know the training sample size is related to time needed and memory usage. I tried all 2000 samples but still got memory not enough error. May I know what training sample size you used?

**Comment by RoboPai** [comment]
I used 6666 samples to train my model, and my machine's memory is 32G

**Comment by cpfe532** [comment]
Thanks, I tried 500 only which is the size I can use for training, but the detection result is horrible. Let me try all 6666 samples and see what I can get.
